name: buttermanager
version: "2.2"
summary: Graphical tool to manage BTRFS filesystems
description: Manage a BTRFS filesystem with this easy to use Graphical User Interface application programmed in Python and QT5. Create BTRFS snapshots, balance filesystems and upgrade the system safetly.
type: app
grade: stable
base: core16
confinement: classic

apps:
  buttermanager:
    command: bin/buttermanager.sh
    environment:
      DISABLE_WAYLAND: 1

parts:
  # Pulls the code of desktop-qt5 part
  desktop-qt5:
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
      - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - appmenu-qt5
      - locales-all
  # Pulls the code from the original source (master branch)
  # desktop-qt5 is a snapcraft part (snapcraft-desktop-helpers) from the Wiki: https://wiki.ubuntu.com/snapcraft/parts
  # It enables desktop integration for QT5 applications
  # Github repository for snapcraft-desktop-helpers: https://github.com/ubuntu/snapcraft-desktop-helpers
  buttermanager:
    plugin: python
    python-version: python3
    source: ../
    # python3-pyqt5 is necessary for the application to run because PyQT5 has been used to code ButterManager
    # The rest of the python dependencies are not necessary because they will be included
    # when setup.py is executed by python snapcraft plugin
    stage-packages:
      - btrfs-tools
      - python3-pyqt5
      - python3-yaml
      - python3-sip
    after: [desktop-qt5]

  # It will copy all the Python code needed for running the application
  # into buttermanager directory
  structure:
    plugin: dump
    source: ./buttermanager
    organize:
      '*': buttermanager/

  # It will copy buttermanager script into /bin/
  # This script contains all the commands needed to execute the application
  wrapper:
    plugin: dump
    source: scripts
